"""
Load test_data.json into PostgreSQL for demo.
Requires: test_data.json generated by generate_test_data.py
Run: python scripts/load_sample_data.py
"""
from __future__ import annotations
import json
import sys
from pathlib import Path
from datetime import datetime, timezone

PROD_KEYWORDS = ("prod", "production", "bling_prod", "live")


def _check_not_prod(url: str) -> None:
    if any(kw in url.lower() for kw in PROD_KEYWORDS):
        print("ERROR: Refusing to seed — POSTGRES_URL looks like a production database.")
        sys.exit(1)


def main() -> None:
    from app.core.config import settings
    _check_not_prod(settings.postgres_url)

    data_file = Path("test_data.json")
    if not data_file.exists():
        print("ERROR: test_data.json not found. Run generate_test_data.py first.")
        sys.exit(1)

    data = json.loads(data_file.read_text())
    transactions = data["transactions"]

    from app.utils.postgres_client import SessionLocal
    from app.models.database import Account, Transaction

    db = SessionLocal()
    try:
        # Collect all unique account IDs and insert accounts
        account_ids = set()
        for t in transactions:
            account_ids.add(t["account_id"])
            if t.get("payee_account_id"):
                account_ids.add(t["payee_account_id"])

        now = datetime.now(timezone.utc)
        existing = {row.id for row in db.query(Account.id).all()}
        new_accounts = [
            Account(
                id=aid,
                account_type="SAVINGS",
                account_age_days=365 + (hash(aid) % 1000),
                kyc_completeness_score=0.8,
                created_at=now,
                updated_at=now,
            )
            for aid in account_ids if aid not in existing
        ]
        db.bulk_save_objects(new_accounts)
        db.flush()
        print(f"Inserted {len(new_accounts)} accounts")

        # Insert transactions in batches of 500
        batch_size = 500
        inserted = 0
        for i in range(0, len(transactions), batch_size):
            batch = transactions[i: i + batch_size]
            rows = []
            for t in batch:
                ts = datetime.fromisoformat(t["timestamp"].replace("Z", "+00:00"))
                rows.append(Transaction(
                    id=t["id"],
                    account_id=t["account_id"],
                    payee_account_id=t.get("payee_account_id"),
                    amount=t["amount"],
                    channel=t["channel"],
                    timestamp=ts,
                ))
            db.bulk_save_objects(rows)
            db.flush()
            inserted += len(rows)
            print(f"  Loaded {inserted}/{len(transactions)} transactions...")

        db.commit()
        print(f"Done. {data['fraud_count']} fraud, {data['legit_count']} legit loaded.")
    except Exception as exc:
        db.rollback()
        print(f"ERROR: {exc}")
        sys.exit(1)
    finally:
        db.close()


if __name__ == "__main__":
    main()
